export { default as authFormStyles } from './auth-form'
export { default as headerStyles } from './header'
export { default as movieSearchStyles } from './movie-search'
export { default as searchResultsStyles } from './search-results'
export { default as singleMovieStyles } from './single-movie'
export { default as searchFormStyles } from './search-form'
export { default as nominationsStyles } from './nominations'
export { default as singleNominationStyles } from './single-nomination'
